### ISSUE TITLE
I'm having trouble running the StyleGAN nodes for ComfyUI!

### ISSUE THREAD

**Issue by Lorenzoidal** [spacepxl/ComfyUI-StyleGan#5]
I downloaded the nodes and installed them just fine, but when I try to run them I get the error: 

"Error occurred when executing LoadStyleGAN:

No module named 'dnnlib.tflib'"

I have downloaded and installed the *.whl file here:

https://github.com/podgorskiy/dnnlib/releases/download/0.0.1/dnnlib-0.0.1-py3-none-any.whl

...But I still get the same error when I try to run those 3 nodes together, as seen in your screenshot.

Can you please help me? I would really, really appreciate it!!

Thanks,
~Loren

**Comment by spacepxl** [comment]
What model are you trying to use? Can you post the full error trace from the console?

**Comment by Lorenzoidal** [comment]
Thank you for the response!

This happens no matter what StyleGAN model I try to use, whether it's trained on 2 or 3.

The nodes all install and load just fine, but when I run the queue in the standalone I get this error message in the console:

`!!! Exception during processing!!! No module named 'dnnlib.tflib' Traceback (most recent call last): File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StyleGan\nodes.py", line 43, in load_stylegan G = pickle.load(f)['G_ema'].cuda() ^^^^^^^^^^^^^^ ModuleNotFoundError: No module named 'dnnlib.tflib'`

**Comment by Lorenzoidal** [comment]
Here is the error from the console:

`!!! Exception during processing!!! No module named 'dnnlib.tflib'
Traceback (most recent call last):
  File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_(07-08)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StyleGan\nodes.py", line 43, in load_stylegan
    G = pickle.load(f)['G_ema'].cuda()
        ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'dnnlib.tflib'`

Thank you again!

**Comment by Lorenzoidal** [comment]
Sorry to bump this, but can you tell me what's going wrong, and how I might fix it? I would really love to be able to use this! Thanks!
